// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCiKOnbfjRyPzgQu7j2pTN4hsmD_JUjJ0',
    appId: '1:415739142672:web:c3f37b61dcd517cbeca095',
    messagingSenderId: '415739142672',
    projectId: 'salon-belleza-2cf6c',
    authDomain: 'salon-belleza-2cf6c.firebaseapp.com',
    storageBucket: 'salon-belleza-2cf6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBss5ho1KqwMFe6gCOHTCDPwjjt_r8aMNQ',
    appId: '1:415739142672:android:416a53ee656bce91eca095',
    messagingSenderId: '415739142672',
    projectId: 'salon-belleza-2cf6c',
    storageBucket: 'salon-belleza-2cf6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2U3GQYhi2wazpwD3U1rzcCtBkHQtLr7Q',
    appId: '1:415739142672:ios:2087bda75bba84f9eca095',
    messagingSenderId: '415739142672',
    projectId: 'salon-belleza-2cf6c',
    storageBucket: 'salon-belleza-2cf6c.firebasestorage.app',
    androidClientId: '415739142672-c8g475874iskcu54vbhv4bcvrf9qjfjq.apps.googleusercontent.com',
    iosClientId: '415739142672-9uabv1nh61e457vmijnv401gofc5lttq.apps.googleusercontent.com',
    iosBundleId: 'com.appsalon.app',
  );

}